### PR TITLE
Fix the deep rooted references for CallbackClient when it's reset

### PR DESCRIPTION
**Pull request by 243826**
Fix the half baked functionality in PR #179.

### CODE REVIEW

**Comment by bartdag** [comment]
The only issue remaining is with concurrency. What if reset is called concurrently or if reset and getCallbackClient are called concurrently (the immutability/final property of callback client was a protection against that :-) )?

One way to avoid going down the rabbit hole of concurrency would be to slightly change the model: allow the creation of a gateway without a callback client and allow the reset (here it would be renamed to set) only if the callback client does not exist. Then you don't even need to care about calling shutdown and removing old references to callback client.

The main limitation would be that it would not support multiple python processes connecting serially with different callback ports (e.g., python process 1 connects than leaves. python process 2 connects and wants to use another port).

Maybe concurrently calling these methods would not be too bad, but I need to think about the various scenarios. There are some places in the python code that are not surrounded by a lock because concurrently calling the methods still yield a correct result, but with more work.

**Comment by bartdag** [comment]
I made some small fixes in 01b0a95. I tried for a while to create a thread-safe version of resetCallbackClient, but in the end there were too many scenarios to consider. I thus indicated that the method is not thread safe.

I also added a few tests on the Java and Python sides and more doc. Do not hesitate to test this new version.

**Comment by 243826** [comment]
Thanks! I am reviewing the code and after pulling in the commit with newly added tests, I find that the python tests are failing. Wondering what I am doing wrong. TestResetCallbackClient fails as well for me:
```
======================================================================
ERROR: testDefaults (py4j.tests.java_gateway_test.GatewayLauncherTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/cnarsude/work/py4j/py4j-python/src/py4j/tests/java_gateway_test.py", line 795, in testDefaults
    self.gateway = JavaGateway.launch_gateway()
  File "/Users/cnarsude/work/py4j/py4j-python/src/py4j/java_gateway.py", line 1556, in launch_gateway
    daemonize_redirect=daemonize_redirect)
  File "/Users/cnarsude/work/py4j/py4j-python/src/py4j/java_gateway.py", line 151, in launch_gateway
    raise Py4JError("Could not find py4j jar at {0}".format(jarpath))
Py4JError: Could not find py4j jar at

======================================================================
ERROR: testJavaopts (py4j.tests.java_gateway_test.GatewayLauncherTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/cnarsude/work/py4j/py4j-python/src/py4j/tests/java_gateway_test.py", line 799, in testJavaopts
    self.gateway = JavaGateway.launch_gateway(javaopts=["-Xmx64m"])
  File "/Users/cnarsude/work/py4j/py4j-python/src/py4j/java_gateway.py", line 1556, in launch_gateway
    daemonize_redirect=daemonize_redirect)
  File "/Users/cnarsude/work/py4j/py4j-python/src/py4j/java_gateway.py", line 151, in launch_gateway
    raise Py4JError("Could not find py4j jar at {0}".format(jarpath))
Py4JError: Could not find py4j jar at

======================================================================
ERROR: testRedirectToDeque (py4j.tests.java_gateway_test.GatewayLauncherTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/cnarsude/work/py4j/py4j-python/src/py4j/tests/java_gateway_test.py", line 826, in testRedirectToDeque
    redirect_stdout=qout, redirect_stderr=qerr)
  File "/Users/cnarsude/work/py4j/py4j-python/src/py4j/java_gateway.py", line 1556, in launch_gateway
    daemonize_redirect=daemonize_redirect)
  File "/Users/cnarsude/work/py4j/py4j-python/src/py4j/java_gateway.py", line 151, in launch_gateway
    raise Py4JError("Could not find py4j jar at {0}".format(jarpath))
Py4JError: Could not find py4j jar at

======================================================================
ERROR: testRedirectToFile (py4j.tests.java_gateway_test.GatewayLauncherTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/cnarsude/work/py4j/py4j-python/src/py4j/tests/java_gateway_test.py", line 846, in testRedirectToFile
    redirect_stdout=stdout, redirect_stderr=stderr)
  File "/Users/cnarsude/work/py4j/py4j-python/src/py4j/java_gateway.py", line 1556, in launch_gateway
    daemonize_redirect=daemonize_redirect)
  File "/Users/cnarsude/work/py4j/py4j-python/src/py4j/java_gateway.py", line 151, in launch_gateway
    raise Py4JError("Could not find py4j jar at {0}".format(jarpath))
Py4JError: Could not find py4j jar at

======================================================================
ERROR: testRedirectToNull (py4j.tests.java_gateway_test.GatewayLauncherTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/cnarsude/work/py4j/py4j-python/src/py4j/tests/java_gateway_test.py", line 803, in testRedirectToNull
    self.gateway = JavaGateway.launch_gateway()
  File "/Users/cnarsude/work/py4j/py4j-python/src/py4j/java_gateway.py", line 1556, in launch_gateway
    daemonize_redirect=daemonize_redirect)
  File "/Users/cnarsude/work/py4j/py4j-python/src/py4j/java_gateway.py", line 151, in launch_gateway
    raise Py4JError("Could not find py4j jar at {0}".format(jarpath))
Py4JError: Could not find py4j jar at

======================================================================
ERROR: testRedirectToQueue (py4j.tests.java_gateway_test.GatewayLauncherTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/cnarsude/work/py4j/py4j-python/src/py4j/tests/java_gateway_test.py", line 811, in testRedirectToQueue
    redirect_stdout=qout, redirect_stderr=qerr)
  File "/Users/cnarsude/work/py4j/py4j-python/src/py4j/java_gateway.py", line 1556, in launch_gateway
    daemonize_redirect=daemonize_redirect)
  File "/Users/cnarsude/work/py4j/py4j-python/src/py4j/java_gateway.py", line 151, in launch_gateway
    raise Py4JError("Could not find py4j jar at {0}".format(jarpath))
Py4JError: Could not find py4j jar at

----------------------------------------------------------------------
Ran 112 tests in 55.396s

FAILED (errors=7)
```

**Comment by 243826** [comment]
Ignore my previous comment. I was using mvn to build the project and it was not copying the py4j jar at an appropriate place.

**Pull request merged**
